### PR TITLE
Allow admins to unassign talks

### PR DESCRIPTION
**Pull request by erinmorrissey**
Updated the User model to allows admins to unassign a talk, and added a test for that scenario.

### CODE REVIEW

**Comment by kenmazaika** [comment]
Looks great to me. Thoughts @colinrubbert?

**Comment by colinrubbert** [comment]
@kenmazaika Looks pretty good to me, I can take a closer look and pull it to my local environment in the morning unless you think it's solid. I'm away from the computer for the night but I've got complete faith that it works :smile: If you think it's good lets merge it!

**Comment by kenmazaika** [comment]
Cool.  Looks good to me.  I'll merge it!

**Comment by colinrubbert** [comment]
w00t! Congrats @erinmorrissey for the contribution!

**Comment by erinmorrissey** [comment]
Awesome, thanks @colinrubbert & @kenmazaika !

**Pull request merged**
