### PR TITLE
Use association for assigning and unassigning talks.

### LINKED ISSUE #7: Talks Assigned and Unassigned

### PR DESCRIPTION
**Pull request by jonmast**
Fixes #7 by checking if current_user == assignee before unassigning a talk. Removes the need for is_assigned and assigned_to columns since we can get that info from the user. Includes a bit of SQL magic in the migration so existing data will work correctly. We probably should test this on a copy of production data before putting it live to make sure there are no problems.

### CODE REVIEW

**Comment by colinrubbert** [comment]
This definitely simplifies things and would be a good addition. The addition like you said would be migrating the correct data. The other addition I would add is the ability to have the first name and first initial of the last name for each assigned card. It helps me out a bunch to be able to see last name initials so that I don't get confused with who assigned it to themselves. We've got multiple Chris' and Jon/John's, it get super confusing, especially if they are talking the same night.

**Comment by jonmast** [comment]
Sorry, I intended to do that and forgot. I'll add a commit for that.

**Comment by colinrubbert** [comment]
Sounds good. Once you add that I'll try and test this tonight, otherwise I'll test tomorrow.

**Comment by colinrubbert** [comment]
Sorry this is taking so long.
Does this automatically update the attributes of the current talks if they are scheduled/assigned? I would hate to have to go through and manually update everything.

**Comment by jonmast** [comment]
Yes it does. That is what the raw sql snippet in the migration is for.

**Comment by colinrubbert** [comment]
I'm going to do this tomorrow after the lightning talks, don't want to run into an issue before hand.

**Comment by colinrubbert** [comment]
This looks to work good. I captured and pulled our Heroku db and restored it locally and it looks like everything is working good. I'm going to make a backup first but I'll be merging this tonight. Great job, another amazing contribution! Keep it up!

**Pull request merged**
