### PR TITLE
Sort unscheduled talks by number of votes

### PR DESCRIPTION
**Pull request by jonmast**
There are quite a few unscheduled talks so it would be nice to sort them by number of votes to see what is popular. I used a counter cache on the votes association to track the number of votes. This allows sorting by number of votes without a complex join.

### CODE REVIEW

**Comment by colinrubbert** [comment]
Good idea @jonmast, I'll take a look at this today or tomorrow when I get a few minutes.

**Comment by jonmast** [comment]
Hey @colinrubbert, did you get a chance to look at this? I noticed it had a merge conflict so I rebased it  against master.

**Comment by colinrubbert** [comment]
@jonmast I've been thinking about it lately and trying to figure out the best approach. I like the idea of having things ordered by votes but then it makes it a mess to go through the list or quickly find a topic (granted this really only takes me less than a minute but when I need to quickly schedule something it's a pain). I think if the app was more active and people were voting more often then I think it's a brilliant idea. 

Can this be sorted alphabetically AND number of votes? Maybe that would be more user friendly. I'm still on the fence about it. I like it in theory but in practice it's less practical, at least for me. 

Thoughts?

**Comment by jonmast** [comment]
How about sorting by assigned, then votes, then alphabetical? That way the topics that are ready to schedule are at the top of the list and topics with the same amount of votes are in alphabetical order.

**Comment by colinrubbert** [comment]
@jonmast I think that could be a good option, why don't we give that a try and see how it looks.

**Comment by jonmast** [comment]
All right, should be ready to go.

**Pull request merged**
