### PR TITLE
Clean up scheduled vs unscheduled

### PR DESCRIPTION
**Pull request by jonmast**

### CODE REVIEW

**Comment by colinrubbert** [comment]
Wow, that's a lot of refactoring. I did find an issue though. 

If you completely remove `@talks = Talk.all` from the index function then it breaks the helper methods which determines how the app displays whether a talk is an `upcoming_talk` or a `previous_talk`. If you could just add `@talks = Talk.all` back into the index and resubmit I would be more than happy to merge.

**Comment by colinrubbert** [comment]
The other option after thinking about it would be to go into the helper methods and change `@talks` to `@scheduled_talks` this seems to work.

**Comment by jonmast** [comment]
Sorry, I can't believe I didn't catch that. I just reworked the logic in the index so we no longer require the helpers and DRYed the previous view as well.

**Comment by jonmast** [comment]
After thinking about this a bit I am wondering if we should add some sort of constraint to keep people from un-assigning scheduled talks. The way it is currently implemented it will show as scheduled even if they un-assign themselves. We could just prevent un-assigning scheduled tasks (once you're in your'e in ;-)) or automatically unschedule the talk if they un-assign it.

**Comment by colinrubbert** [comment]
@jonmast two things:

1st: Awesome job with the code my only caveat and what I would like you to change back is the renders 
`<%= render "partials/previousTalks" if @previous_talks%>` 

back to

```
<% if @previous_talks %>
  <%= render "partials/previousTalks" %>        
<% end %>
```

The reason for this is because these open source contributions projects I've been building for the community are to get people more comfortable with contributing and reading code while also building useful tools for the community. 

I'm a little hesitate to refactoring things to the point where people don't quite grasp what is going on in the code. I think simplifying it to one single line could confuse people. That's my two cents on that. I would be interested in hearing what @kenmazaika view point on how far down the rabbit hole we should go with refactoring. I definitely want to keep ternary operators out of these simple apps.  

2nd: I agree 100% on restricting the unassinged/assigned that's why I put [this](https://github.com/FirehoseCommunity/LightningTalkTopics/issues/7) in the GitHub issues :grin:

**Pull request merged**
