### PR TITLE
Views changed with conditions to show assigned/unassigned

### PR DESCRIPTION
**Pull request by ghost**
Addressing https://github.com/FirehoseCommunity/LightningTalkTopics/issues/7 from the `view`side, only showing unassigned => assigned toggle to signed in users, and assigned => unassigned for the user who was `assigned_to` the talk, or `admin`.

Please make any changes you see fit, otherwise I hope it helps.

### CODE REVIEW

**Comment by colinrubbert** [comment]
@helloramon Thanks for contributing. I am, however, going to hold off on this because we are about to merge in some extensive changes to the view. Your code will still be applicable but I am changing the `first_name` for user to possibly present as first & last name. So hold tight for a couple days until we merge the changes then we'll rock this change!

**Comment by ghost** [comment]
@colinrubbert Sounds good! As always, thanks for your hardwork.

**Comment by colinrubbert** [comment]
@helloramon the new changes have been merged into master. You're going to probably want to do a master pull and then re-apply your changes in the necessary locations. Warning: it's been refactored considerably and a couple other little things have been changed. If you need a hand or have questions just let me know. Sorry ahead of time for the massive changes :smile:

**Comment by colinrubbert** [comment]
I'm going to close this because this issue has been resolved and there have been some major changes to the application. Thanks for the initial work! :+1:

**Pull request closed without merging**
