### PR TITLE
Firehose Lightning Talk App

### PR DESCRIPTION
**Pull request by colinrubbert**
Application for submitting lightning talks and assigning them. This is an MVP and many things will be updated to be more functional.

### CODE REVIEW

**Comment by kenmazaika** [comment]
You're a machine, Colin.  I just checked out the app on heroku [here](https://firehoselightning.herokuapp.com).  Looks like a solid start!

You rock!

**Comment by colinrubbert** [comment]
I'm trying to work on a few other little tweaks before I populate and announce the talks. Adding first & last names to devise is a pain.

**Comment by kenmazaika** [comment]
Cool!  I'm really excited about this.  Should add a lot of organization and streamlining of the lightning talks.

The trick is to add the fields into the `devise_parameter_sanitizer` in `application_controller.rb`.

http://jacopretorius.net/2014/03/adding-custom-fields-to-your-devise-user-model-in-rails-4.html

That's how you can shoe-horn those into the magic devise controller's "strong params".

**Comment by colinrubbert** [comment]
I just found that and go it setup but it was a pain for find the right info since there was differences between rails 3 and 4.

**Comment by colinrubbert** [comment]
This is what it will look like with populated talks. I haven't added anything to Heroku yet. 

firehose_lightning

**Comment by kenmazaika** [comment]
Solid!  This is awesome!

**Pull request merged**
